# Generated by Django 4.1.7 on 2023-03-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category_alter_listing_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='seller',
            new_name='seller_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.FloatField(null=True),
        ),
    ]
