# Generated by Django 4.1.7 on 2023-03-11 15:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_seller_id_listing_seller_listing_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='listing',
            name='datetime_posted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 11, 15, 53, 27, 104007)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
