# Generated by Django 4.1.7 on 2023-03-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listing_date_posted_listing_datetime_posted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='listing_title',
        ),
    ]
