# Generated by Django 4.1.7 on 2023-03-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_title_listing_listing_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='datetime_posted',
            new_name='posted_datetime',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='seller',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
    ]
